language: node_js
node_js:
  - 10
branches:
  only:
    - master
    - v1.5_service_annotation
    - v2
install:
  - npm install -g lerna
  - lerna bootstrap
  - npm install
script:
  - lerna run test
  - lerna run test:coverage
  - npm run docs:prod
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: v2

